package com.walfrosch92.mealie_recipes.wear

/**
 * Statische Übersetzungstabelle für die Wear-OS-App.
 *
 * Die Uhr nutzt bewusst KEIN system-locale-basiertes `values-<lang>/strings.xml`
 * für diese Texte: die App hat eine EIGENE, von der Systemsprache der Uhr
 * unabhängige Sprachauswahl (`AppSettings.selectedLanguage`), die per
 * WearBridge/[LanguageRepository] auf die Uhr gespiegelt wird — genau wie
 * Timer/Kochmodus/Einkaufsliste. Android-Ressourcen-Qualifier würden
 * stattdessen der SYSTEMSPRACHE der Uhr folgen, die vom App-internen
 * Sprachwechsel abweichen kann. Deckt dieselben Keys ab wie die iOS-Seite
 * (siehe `ios/Mealie Recipes Watch App/WatchL10n.swift`) — bei neuen Strings
 * BEIDE Tabellen pflegen.
 */
object WearStrings {
    fun t(key: String, lang: String): String =
        table[lang]?.get(key) ?: table.getValue("de").getValue(key)

    private val table: Map<String, Map<String, String>> = mapOf(
        "de" to mapOf(
            "noActiveTimer" to "Kein aktiver Timer",
            "openPhoneHint" to "Starte einen Timer im Kochmodus auf dem Handy.",
            "pause" to "Pausieren",
            "resume" to "Fortsetzen",
            "stop" to "Stoppen",
            "channelTimer" to "Timer",
            "shoppingHeader" to "Einkaufen",
            "shoppingEmpty" to "Keine offenen Artikel",
            "shoppingTileLabel" to "Einkaufsliste",
            "completed" to "Erledigt",
            "open" to "Offen",
            "uncategorized" to "Sonstiges",
            "back" to "Zurück",
            "next" to "Weiter",
        ),
        "en" to mapOf(
            "noActiveTimer" to "No active timer",
            "openPhoneHint" to "Start a timer in cooking mode on your phone.",
            "pause" to "Pause",
            "resume" to "Resume",
            "stop" to "Stop",
            "channelTimer" to "Timer",
            "shoppingHeader" to "Shopping",
            "shoppingEmpty" to "No open items",
            "shoppingTileLabel" to "Shopping List",
            "completed" to "Completed",
            "open" to "Open",
            "uncategorized" to "Other",
            "back" to "Back",
            "next" to "Next",
        ),
        "es" to mapOf(
            "noActiveTimer" to "Sin temporizador activo",
            "openPhoneHint" to "Inicia un temporizador en el modo de cocina en tu teléfono.",
            "pause" to "Pausar",
            "resume" to "Reanudar",
            "stop" to "Detener",
            "channelTimer" to "Temporizador",
            "shoppingHeader" to "Compras",
            "shoppingEmpty" to "Sin artículos pendientes",
            "shoppingTileLabel" to "Lista de compras",
            "completed" to "Completado",
            "open" to "Abierto",
            "uncategorized" to "Otros",
            "back" to "Atrás",
            "next" to "Siguiente",
        ),
        "fr" to mapOf(
            "noActiveTimer" to "Aucun minuteur actif",
            "openPhoneHint" to "Démarrez un minuteur en mode cuisine sur votre téléphone.",
            "pause" to "Mettre en pause",
            "resume" to "Reprendre",
            "stop" to "Arrêter",
            "channelTimer" to "Minuteur",
            "shoppingHeader" to "Courses",
            "shoppingEmpty" to "Aucun article en attente",
            "shoppingTileLabel" to "Liste de courses",
            "completed" to "Terminé",
            "open" to "Ouvert",
            "uncategorized" to "Autres",
            "back" to "Retour",
            "next" to "Suivant",
        ),
        "hu" to mapOf(
            "noActiveTimer" to "Nincs aktív időzítő",
            "openPhoneHint" to "Indíts egy időzítőt a főzési módban a telefonon.",
            "pause" to "Szünet",
            "resume" to "Folytatás",
            "stop" to "Leállítás",
            "channelTimer" to "Időzítő",
            "shoppingHeader" to "Bevásárlás",
            "shoppingEmpty" to "Nincs nyitott tétel",
            "shoppingTileLabel" to "Bevásárlólista",
            "completed" to "Kész",
            "open" to "Nyitott",
            "uncategorized" to "Egyéb",
            "back" to "Vissza",
            "next" to "Tovább",
        ),
        "nl" to mapOf(
            "noActiveTimer" to "Geen actieve timer",
            "openPhoneHint" to "Start een timer in de kookmodus op je telefoon.",
            "pause" to "Pauzeren",
            "resume" to "Hervatten",
            "stop" to "Stoppen",
            "channelTimer" to "Timer",
            "shoppingHeader" to "Boodschappen",
            "shoppingEmpty" to "Geen openstaande artikelen",
            "shoppingTileLabel" to "Boodschappenlijst",
            "completed" to "Voltooid",
            "open" to "Open",
            "uncategorized" to "Overig",
            "back" to "Terug",
            "next" to "Volgende",
        ),
        "pl" to mapOf(
            "noActiveTimer" to "Brak aktywnego minutnika",
            "openPhoneHint" to "Uruchom minutnik w trybie gotowania na telefonie.",
            "pause" to "Wstrzymaj",
            "resume" to "Wznów",
            "stop" to "Zatrzymaj",
            "channelTimer" to "Minutnik",
            "shoppingHeader" to "Zakupy",
            "shoppingEmpty" to "Brak otwartych pozycji",
            "shoppingTileLabel" to "Lista zakupów",
            "completed" to "Zrobione",
            "open" to "Otwarte",
            "uncategorized" to "Inne",
            "back" to "Wstecz",
            "next" to "Dalej",
        ),
        "pt" to mapOf(
            "noActiveTimer" to "Nenhum timer ativo",
            "openPhoneHint" to "Inicie um timer no modo de cozinhar no celular.",
            "pause" to "Pausar",
            "resume" to "Retomar",
            "stop" to "Parar",
            "channelTimer" to "Timer",
            "shoppingHeader" to "Compras",
            "shoppingEmpty" to "Nenhum item pendente",
            "shoppingTileLabel" to "Lista de compras",
            "completed" to "Concluído",
            "open" to "Aberto",
            "uncategorized" to "Outros",
            "back" to "Voltar",
            "next" to "Próximo",
        ),
        "sl" to mapOf(
            "noActiveTimer" to "Ni aktivnega časovnika",
            "openPhoneHint" to "Zaženi časovnik v načinu kuhanja v telefonu.",
            "pause" to "Premor",
            "resume" to "Nadaljuj",
            "stop" to "Ustavi",
            "channelTimer" to "Časovnik",
            "shoppingHeader" to "Nakupovanje",
            "shoppingEmpty" to "Ni odprtih artiklov",
            "shoppingTileLabel" to "Nakupovalni seznam",
            "completed" to "Končano",
            "open" to "Odprto",
            "uncategorized" to "Drugo",
            "back" to "Nazaj",
            "next" to "Naprej",
        ),
        "nb" to mapOf(
            "noActiveTimer" to "Ingen aktiv timer",
            "openPhoneHint" to "Start en timer i kokemodus på telefonen.",
            "pause" to "Pause",
            "resume" to "Fortsett",
            "stop" to "Stopp",
            "channelTimer" to "Timer",
            "shoppingHeader" to "Handling",
            "shoppingEmpty" to "Ingen åpne varer",
            "shoppingTileLabel" to "Handleliste",
            "completed" to "Fullført",
            "open" to "Åpen",
            "uncategorized" to "Annet",
            "back" to "Tilbake",
            "next" to "Neste",
        ),
    )
}
